### ISSUE TITLE
Feature Name :  [ 1.05 Landing/Login Page - Text Field Memory ]

### ISSUE THREAD

**Issue by akibrhast** [akibrhast/VRMS#6]
### Description
As a returning user, I want VRMS to remember previous inputs in the landing page text field so I don’t have to retype my email address repeatedly.

### Acceptance Criteria

- Previously entered email addresses are remembered/suggested for landing page email address field

### Tasks

- [ ] https://github.com/hackforla/VRMS/issues/592

- [ ] https://github.com/hackforla/VRMS/issues/593

- [ ] https://github.com/hackforla/VRMS/issues/594
